.TH jobber 1 "13 Oct 2013" "version 0.1" 
.SH NAME 
jobber - Console work time tracker

.SH SYNOPSIS
\fBjobber\fR [\fIOPTIONS\fR]
.SH DESCRIPTION

Jobber is a console tool which might help you to track your work time. 

.SS "Job Creation:"

\fB-s\fR, \fB--start\fR [\fITIME\fR]
        Start work now or at the given \fITIME\fR. If you add \fB-m\fR you will explicitly be asked for a message to add.

\fB-e\fR, \fB--end\fR [\fITIME\fR]
        End work now or at the given \fITIME\fR. You will be asked to enter a message if none was given before for that job. 

\fB-b\fR, \fB--back\fR [\fITIME\fR]
        "Back to work" (now or at \fITIME\fR)copies message from last closed job and start a new one with that message.

\fB-c\fR, \fB--cancel\fR
        Cancel the running job and delete it from data base.

\fB-d\fR, \fB--duration\fR \fIHOURS\fR
        Defines the end time if you gave a starting time with \fI-s\fR and
        the start time if you gave an ending time with \fI-e\fR.

\fB-m\fR, \fB--message\fR [\fIMESSAGE\fR]
        Add a message to the starting, ending or running job. Asks for \fIMESSAGE\fR if not given by parameter.

.SS "Parameter Formats:"

.IP \fITIME\fR 
has to describe an absolute time that can be given in any of these formats:

.TP 20
Time relatively from now:
.TP
now
Realy now!
.TP
4:10-
4 hours and 10 minutes ago
.TP
1h+
in 1 hour
.TP
14:10
today at 14:10
.TP
Date relatively from today:
.TP 20
8/1/,14:10
at 1st of August this year at 14:10
.TP
mon,14:10
last monday at 14:10
.TP
yesterday,14:10
yesterday at 14:10
.TP
Absolute date and time:
.TP 20
8/1/2012,14:10
at 1st of August 2012 at 14:10
  
.IP \fIRANGE\fR
describes a time range:

.TP 20
\fITIME1\fR..\fITIME2\fR
from TIME1 until TIME2
.TP
\fITIME\fR..
from TIME until now
.TP
..\fITIME\fR
from big bang until TIME

.SS Job manipulation:

\fB-j\fR, \fB--join\fR \fIPOS1\fR,\fIPOS2\fR,...
        Join two or more jobs at the given positions. 

\fB-D\fR, \fB--drop\fR \fIPOS\fR
        Drop job at the given position.

.SS Colors:
.TP 15
green 
Start times
.TP
magenta
End times
.TP
bold/white
Job Messages
.TP
blue
Action messages mark the beginning of data base modifications.
.TP
brown
Warning messages warn you of exceptional results.
.TP
red
Error messages mark failed actions.

.SS Reporting:

\fB-l\fR, \fB--list\fR [\fITIME\fR|\fIRANGE\fR|\fICOUNT\fR]
        List all jobs or all jobs since \fITIME\fr, within \fIRANGE\fR or the last \fICOUNT\fR jobs.
 
\fB-t\fR, \fB--total\fR [\fITIME\fR|\fIRANGE\fR|\fICOUNT\fR]
        Measure totals of all jobs or all jobs since \fITIME\fr, within \fIRANGE\fR or the last \fICOUNT\fR jobs.

\fB-r\fR, \fB--report\fR
        Monthly report existing jobs.

\fB-R\fR, \fB--resolution\fR [\fIRESOLUTION\fR]
        Time resolution to round work times (default: 0.25).

\fB-M\fR, \fB--money\fR [\fIRATE\fR]
        Display hours*\fIRATE\fR in report and list. 

.SS "Data base configuration:"

\fB-f\fR, \fB--file\fR \fIFILENAME\fR
        Data base file to use (default: ./jobber.dat)

.SS "Common options:"

\fB-v\fR, \fB--verbose\fR
        Output more information

\fB-h\fR, \fB--help\fR
        Display this screen


.SH COPYRIGHT
  Free to copy. See http://github.com/patgithub/jobber for source code

.SH AUTHOR
  Patrick Hoffmann (p.hoffmann@berlin.de)
